minimum_pre_commit_version: "1.13.0"
repos:
  - repo: https://github.com/psf/black
    rev: "19.10b0"
    hooks:
      - id: black
        name: Format code (black)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v2.4.0"
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://gitlab.com/PyCQA/flake8
    rev: "3.7.9"
    hooks:
      - id: flake8
        name: Lint code (flake8)
        additional_dependencies:
          - flake8==3.7.9
          - flake8-broken-line==0.1.1
          - flake8-bugbear==20.1.0
          - flake8-builtins==1.4.2
          - flake8-comprehensions==3.1.4
          - flake8-import-order==0.18.1
          - flake8-mutable==1.2.0
          - flake8-pie==0.4.2
          - flake8-quotes==2.1.1
          - flake8-string-format==0.2.3
          - flake8-tidy-imports==3.1.0
          - pep8-naming==0.9.1
