minimum_pre_commit_version: "2.10.0"
repos:
  - repo: https://github.com/psf/black
    rev: "21.6b0"
    hooks:
      - id: black
        name: Format code (black)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.0.1"
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pycqa/flake8
    rev: "3.9.2"
    hooks:
      - id: flake8
        name: Lint code (flake8)
        additional_dependencies:
          - flake8>=3.8.4
          - flake8-broken-line>=0.3.0
          - flake8-bugbear>=20.11.1
          - flake8-builtins>=1.5.3
          - flake8-comprehensions>=3.3.1
          - flake8-import-order>=0.18.1
          - flake8-mutable>=1.2.0
          - flake8-pie>=0.6.1
          - flake8-quotes>=3.2.0
          - flake8-string-format>=0.3.0
          - flake8-tidy-imports>=4.2.1
          - pep8-naming>=0.11.1
  - repo: "https://github.com/pre-commit/mirrors-mypy"
    rev: "v0.902"
    hooks:
      - id: "mypy"
        name: "Check type hints (mypy)"
        verbose: true
ci:
  autofix_commit_msg: |
      [pre-commit.ci] auto fixes from pre-commit.com hooks

      for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: monthly
  skip: []
  submodules: false
