name: testing

on:
  pull_request:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Run Poetry image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.11

      - name: Install library
        run: poetry install --no-interaction

      - name: Run tests
        run: poetry run pytest

      - name: Upload coverage
        # if: ${{ github.ref == 'refs/heads/master' }}
        uses: codecov/codecov-action@v2
