name: CI

on:
  pull_request:
  push:
    branches: [master]

jobs:
  test-and-publish-flow:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Run Poetry image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.7.1

      - name: Install library
        run: poetry install --no-interaction

      - name: Run tests
        run: poetry run pytest

        # upload coverage only on master branch
      - name: Upload coverage
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: codecov/codecov-action@v2

        # publish version only when pyproject.toml is changed in master
      - name: Filter changes in pyproject
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            root:
              - 'pyproject.toml'

      - if: ${{ (github.ref == 'refs/heads/master') && (steps.changes.outputs.root == 'true')}}
        name: Build
        run: poetry build

      - if: ${{ (github.ref == 'refs/heads/master') && (steps.changes.outputs.root == 'true')}}
        name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
